# Generated by Django 5.2.6 on 2025-09-17 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата операции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('Бизнес', 'Бизнес'), ('Личное', 'Личное'), ('Налог', 'Налог')], max_length=20, verbose_name='Статус')),
                ('operation_type', models.CharField(max_length=20, verbose_name='Тип операции')),
                ('category', models.CharField(max_length=20, verbose_name='Категория')),
                ('subcategory', models.CharField(max_length=20, verbose_name='Подкатегория')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
